server:
  port: 9009
spring:
  application:
    name: tensquare\u2010sms #\u6307\u5B9A\u670D\u52A1\u540D
  rabbitmq:
    host: 172.17.215.130
aliyun:
  sms:
    accessKeyId: \u4E0D\u544A\u8BC9\u4F60
    accessKeySecret: \u4E0D\u544A\u8BC9\u4F60
    template_code: SMS_85735065
    sign_name: clownfish

