server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    url: jdbc:mysql://172.17.208.245:3306/tensquare_base?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true