server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/clownfish7/tensquare_dev.git
  rabbitmq:
    host: 172.17.215.5
#暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh