server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    url: jdbc:mysql://172.17.215.135:3306/tensquare_friend?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
jwt:
  config:
    key: mysalt
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true