server:
  port: 9012
spring:
  application:
    name: tensquare-web
jwt:
  config:
    key: mysalt
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare-base:
      path: /base/**
      serviceId: tensquare-base
    tensquare-article:
      path: /article/**
      serviceId: tensquare-article
    tensquare-gathering:
      path: /gathering/**
      serviceId: tensquare-gathering
    tensquare-qa:
      path: /qa/**
      serviceId: tensquare-qa
    tensquare-recruit:
      path: /recruit/**
      serviceId: tensquare-recruit
    tensquare-search:
      path: /search/**
      serviceId: tensquare-search
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user
